// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gapytkueymkmuadnfihc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcHl0a3VleW1rbXVhZG5maWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNjI2OTgsImV4cCI6MjA4MjkzODY5OH0.Zdy5mPiT2A6PpGsehfmPa-FHYsjNQWze36YUExtjQp0";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
